/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cookbook.gui;

import eu.dominiktousek.pv168.cookbook.Ingredient;
import eu.dominiktousek.pv168.cookbook.IngredientManagerImpl;
import java.awt.event.InvocationEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Dominik
 */
public class AddEditIngredient extends javax.swing.JFrame {

    private final Ingredient ingr;

    /**
     * Creates new form AddEditIngredient
     */
    public AddEditIngredient(Ingredient ing) {
        ingr = ing;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        buttCancel = new javax.swing.JButton();
        buttOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(453, 95));
        setMinimumSize(new java.awt.Dimension(453, 95));
        setPreferredSize(new java.awt.Dimension(453, 95));
        setResizable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mycompany/cookbook/gui/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("name")); // NOI18N
        jLabel1.setToolTipText("");

        if(ingr != null){
            fieldName.setText(ingr.getName());
        }

        buttCancel.setText(bundle.getString("cancel")); // NOI18N
        buttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCancelActionPerformed(evt);
            }
        });

        buttOK.setText(bundle.getString("ok")); // NOI18N
        buttOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 294, Short.MAX_VALUE)
                        .addComponent(buttCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttCancel)
                    .addComponent(buttOK))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCancelActionPerformed
        super.dispose();
    }//GEN-LAST:event_buttCancelActionPerformed

    private void buttOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttOKActionPerformed
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mycompany/cookbook/gui/Bundle");
        
        String name = fieldName.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    bundle.getString("empty name"),
                    "",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        (new EditIngredientWorker(name)).execute();        
        this.dispose();
    }//GEN-LAST:event_buttOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCancel;
    private javax.swing.JButton buttOK;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private class EditIngredientWorker extends SwingWorker<Integer, Void> {
        
        private String name;
        
        public EditIngredientWorker(String name){
            this.name=name;
        }
        
        
        @Override
        protected Integer doInBackground() throws Exception {
            IngredientManagerImpl man = new IngredientManagerImpl();
            if(ingr == null){
                Ingredient in = new Ingredient();
                in.setName(name);
                man.createIngredient(in);
                return 1;
            }            
            ingr.setName(name);
            man.updateIngredient(ingr);
            return 2;
        }
    }
}
